package com.sovworks.eds.fdstest;

import android.content.Context;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.nio.charset.Charset;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * The two-volume fixture and the manifest that says what is supposed to be inside it.
 *
 * Shared by every test that needs it rather than copied into each, because the manifest is
 * the ORACLE: two tests reading it two ways can disagree about what the container should
 * contain and both still pass. The passphrases here are the fixture's own, generated by
 * tools/mkhiddenfixture.sh and committed to the manifest on purpose; they protect nothing.
 */
final class HiddenFixture
{
    static final Charset UTF8 = Charset.forName("UTF-8");
    static final String CONTAINER = "hidden_AES_SHA_512.hc";

    final File container;
    final String outerPassphrase;
    final String hiddenPassphrase;
    /** Path inside the hidden volume to its SHA-256, in manifest order. */
    final Map<String, String> hiddenContents;

    /**
     * Throws rather than returning null when anything is missing. A fixture loader that
     * hands back an empty object turns "the fixtures were never pushed" into a test that
     * quietly measures nothing.
     */
    static HiddenFixture load(Context ctx) throws IOException
    {
        File dir = FixtureSet.locate(ctx);
        if (dir == null)
            throw new IOException("no external files dir on this device");

        File container = new File(dir, CONTAINER);
        File manifest = new File(dir, "hidden-manifest.tsv");
        if (!manifest.isFile())
            throw new IOException("hidden fixture manifest missing: " + manifest.getAbsolutePath()
                    + " (run tools/mkhiddenfixture.sh then tools/run-fixture-tests.sh)"
                    + FixtureSet.describePath(manifest));

        String outer = null, hidden = null;
        Map<String, String> contents = new LinkedHashMap<>();
        BufferedReader r = new BufferedReader(new InputStreamReader(new FileInputStream(manifest), UTF8));
        try
        {
            String line;
            boolean header = true;
            while ((line = r.readLine()) != null)
            {
                if (header) { header = false; continue; }
                if (line.trim().isEmpty()) continue;
                String[] f = line.split("\t", -1);
                if (f.length != 4)
                    throw new IOException("hidden-manifest.tsv needs 4 columns: " + line);
                if ("outer".equals(f[0]))
                    outer = f[1];
                else if ("hidden".equals(f[0]))
                {
                    hidden = f[1];
                    contents.put(f[2], f[3]);
                }
            }
        }
        finally
        {
            r.close();
        }
        return new HiddenFixture(container, outer, hidden, contents);
    }

    /**
     * A scratch copy under the app's cache dir. Every test writes to a copy: the point of
     * several of them is to DESTROY the hidden volume, and a fixture that has been destroyed
     * once makes every later run of every other test meaningless.
     */
    File copy(File scratchDir, String tag) throws IOException
    {
        if (!scratchDir.isDirectory() && !scratchDir.mkdirs())
            throw new IOException("cannot create " + scratchDir);
        File out = new File(scratchDir, tag + "_" + container.getName());
        InputStream in = new FileInputStream(container);
        try
        {
            OutputStream os = new FileOutputStream(out);
            try
            {
                byte[] buf = new byte[64 * 1024];
                int n;
                while ((n = in.read(buf)) > 0)
                    os.write(buf, 0, n);
                os.flush();
            }
            finally
            {
                os.close();
            }
        }
        finally
        {
            in.close();
        }
        if (out.length() != container.length())
            throw new IOException("short copy: " + out.length() + " of " + container.length());
        return out;
    }

    /** What a caller should assert before trusting anything else here. */
    String whatIsMissing()
    {
        if (!container.isFile())
            return "hidden fixture container missing: " + container;
        if (outerPassphrase == null || outerPassphrase.isEmpty())
            return "no outer passphrase in the manifest";
        if (hiddenPassphrase == null || hiddenPassphrase.isEmpty())
            return "no hidden passphrase in the manifest";
        if (hiddenContents.isEmpty())
            return "the manifest lists no files for the hidden volume, so \"the hidden volume "
                    + "survived\" would be true of an empty volume too";
        return null;
    }

    private HiddenFixture(File container, String outer, String hidden, Map<String, String> contents)
    {
        this.container = container;
        this.outerPassphrase = outer;
        this.hiddenPassphrase = hidden;
        this.hiddenContents = Collections.unmodifiableMap(contents);
    }
}
