/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sovworks_eds_crypto_modes_CFB */

/* FDS port note: the checked-in upstream copy of this file was stale javah
 * output taken before CFB moved from com.sovworks.eds.crypto to
 * com.sovworks.eds.crypto.modes. It declared five
 * entry points under the old com.sovworks.eds.crypto.CFB name that nothing implements and
 * exported a com_sovworks_eds_crypto_CFB_SECTOR_SIZE constant that CFB.java no
 * longer declares. Corrected here against CFB.java and edscfb.c, which agree. */

#ifndef _Included_com_sovworks_eds_crypto_modes_CFB
#define _Included_com_sovworks_eds_crypto_modes_CFB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sovworks_eds_crypto_modes_CFB
 * Method:    initContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_sovworks_eds_crypto_modes_CFB_initContext
  (JNIEnv *, jobject);

/*
 * Class:     com_sovworks_eds_crypto_modes_CFB
 * Method:    closeContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_modes_CFB_closeContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sovworks_eds_crypto_modes_CFB
 * Method:    attachNativeCipher
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_modes_CFB_attachNativeCipher
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_sovworks_eds_crypto_modes_CFB
 * Method:    encrypt
 * Signature: ([BII[BJ)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_crypto_modes_CFB_encrypt
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jlong);

/*
 * Class:     com_sovworks_eds_crypto_modes_CFB
 * Method:    decrypt
 * Signature: ([BII[BJ)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_crypto_modes_CFB_decrypt
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
