/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sovworks_eds_crypto_blockciphers_Twofish */

/* FDS port note: the checked-in upstream copy of this file was stale javah
 * output taken before Twofish moved from com.sovworks.eds.crypto to
 * com.sovworks.eds.crypto.blockciphers. It declared four
 * entry points under the old com.sovworks.eds.crypto.Twofish name that nothing implements,
 * leaving the four real entry points without a prototype. Corrected here
 * against Twofish.java and edstwofish.c, which agree. */

#ifndef _Included_com_sovworks_eds_crypto_blockciphers_Twofish
#define _Included_com_sovworks_eds_crypto_blockciphers_Twofish
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sovworks_eds_crypto_blockciphers_Twofish
 * Method:    initContext
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_sovworks_eds_crypto_blockciphers_Twofish_initContext
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_sovworks_eds_crypto_blockciphers_Twofish
 * Method:    closeContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_blockciphers_Twofish_closeContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sovworks_eds_crypto_blockciphers_Twofish
 * Method:    encrypt
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_blockciphers_Twofish_encrypt
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     com_sovworks_eds_crypto_blockciphers_Twofish
 * Method:    decrypt
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_blockciphers_Twofish_decrypt
  (JNIEnv *, jobject, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
