/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sovworks_eds_crypto_modes_CBC */

/* FDS port note: the checked-in upstream copy of this file was stale javah
 * output taken before CBC moved from com.sovworks.eds.crypto to
 * com.sovworks.eds.crypto.modes. It declared five entry points under the old
 * com.sovworks.eds.crypto.CBC name that nothing implements, gave
 * encrypt/decrypt the pre-refactor
 * arity (no trailing boolean incrementIV), and exported a
 * com_sovworks_eds_crypto_CBC_SECTOR_SIZE constant that CBC.java no longer
 * declares. Corrected here against CBC.java and edscbc.c, which agree. */

#ifndef _Included_com_sovworks_eds_crypto_modes_CBC
#define _Included_com_sovworks_eds_crypto_modes_CBC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sovworks_eds_crypto_modes_CBC
 * Method:    initContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_sovworks_eds_crypto_modes_CBC_initContext
  (JNIEnv *, jobject);

/*
 * Class:     com_sovworks_eds_crypto_modes_CBC
 * Method:    closeContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_modes_CBC_closeContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sovworks_eds_crypto_modes_CBC
 * Method:    attachNativeCipher
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_modes_CBC_attachNativeCipher
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_sovworks_eds_crypto_modes_CBC
 * Method:    encrypt
 * Signature: ([BII[BJZ)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_crypto_modes_CBC_encrypt
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jlong, jboolean);

/*
 * Class:     com_sovworks_eds_crypto_modes_CBC
 * Method:    decrypt
 * Signature: ([BII[BJZ)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_crypto_modes_CBC_decrypt
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
