/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sovworks_eds_crypto_blockciphers_GOST */

/* FDS port note: the checked-in upstream copy of this file was stale javah
 * output taken before GOST moved from com.sovworks.eds.crypto to
 * com.sovworks.eds.crypto.blockciphers. It declared four
 * entry points under the old com.sovworks.eds.crypto.GOST name that nothing implements, leaving
 * the four real entry points without a prototype. Corrected here against
 * GOST.java and edsgost.c, which agree. */

#ifndef _Included_com_sovworks_eds_crypto_blockciphers_GOST
#define _Included_com_sovworks_eds_crypto_blockciphers_GOST
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sovworks_eds_crypto_blockciphers_GOST
 * Method:    initContext
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_sovworks_eds_crypto_blockciphers_GOST_initContext
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_sovworks_eds_crypto_blockciphers_GOST
 * Method:    closeContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_blockciphers_GOST_closeContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sovworks_eds_crypto_blockciphers_GOST
 * Method:    encrypt
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_blockciphers_GOST_encrypt
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     com_sovworks_eds_crypto_blockciphers_GOST
 * Method:    decrypt
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_blockciphers_GOST_decrypt
  (JNIEnv *, jobject, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
