/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sovworks_eds_crypto_modes_CTR */

/* FDS port note: the checked-in upstream copy of this file was not CTR's header
 * at all. It was a copy of the pre-refactor CFB header: every declaration named
 * under the old com.sovworks.eds.crypto.CFB name, so the CTR translation unit declared five
 * CFB symbols that nothing implements while its own five entry points had no
 * prototype. It also exported a com_sovworks_eds_crypto_CFB_SECTOR_SIZE
 * constant that no Java class declares. Corrected here against CTR.java and
 * edsctr.c, which agree. */

#ifndef _Included_com_sovworks_eds_crypto_modes_CTR
#define _Included_com_sovworks_eds_crypto_modes_CTR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sovworks_eds_crypto_modes_CTR
 * Method:    initContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_sovworks_eds_crypto_modes_CTR_initContext
  (JNIEnv *, jobject);

/*
 * Class:     com_sovworks_eds_crypto_modes_CTR
 * Method:    closeContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_modes_CTR_closeContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sovworks_eds_crypto_modes_CTR
 * Method:    attachNativeCipher
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_sovworks_eds_crypto_modes_CTR_attachNativeCipher
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_sovworks_eds_crypto_modes_CTR
 * Method:    encrypt
 * Signature: ([BII[BJ)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_crypto_modes_CTR_encrypt
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jlong);

/*
 * Class:     com_sovworks_eds_crypto_modes_CTR
 * Method:    decrypt
 * Signature: ([BII[BJ)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_crypto_modes_CTR_decrypt
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
